name: immrax
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - ampl-asl=1.0.0=h5888daf_2
  - asttokens=3.0.0=pyhd8ed1ab_1
  - brotli=1.1.0=hb03c661_4
  - brotli-bin=1.1.0=hb03c661_4
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py312hd9148b4_2
  - cpython=3.12.12=py312hd8ed1ab_1
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyipopt=1.6.1=py312hf992d99_1
  - debugpy=1.8.17=py312h8285ef7_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - fonttools=4.60.1=py312h8a5da7c_0
  - freetype=2.14.1=ha770c72_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py312h5eee18b_0
  - icu=73.1=h6a678d5_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - iniconfig=2.1.0=py312h06a4308_0
  - ipopt=3.14.19=h0804adb_0
  - ipykernel=7.1.0=pyha191276_0
  - ipympl=0.9.8=pyhcf101f3_0
  - ipython=9.6.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.7=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - jupyterlab_widgets=3.0.15=pyhd8ed1ab_0
  - kiwisolver=1.4.9=py312h0a2e395_1
  - krb5=1.21.3=h723845a_4
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h0aef613_1
  - libblas=3.9.0=37_h4a7cf45_openblas
  - libbrotlicommon=1.1.0=hb03c661_4
  - libbrotlidec=1.1.0=hb03c661_4
  - libbrotlienc=1.1.0=hb03c661_4
  - libcblas=3.9.0=37_h0358290_openblas
  - libdeflate=1.22=hb9d3cd8_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.4=h6a678d5_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h767d61c_6
  - libgcc-ng=15.2.0=h69a702a_6
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran-ng=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libgomp=15.2.0=h767d61c_6
  - libhwloc=2.12.1=default_h3d81e11_1000
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - libkrb5=1.21.3=h520c7b4_4
  - liblapack=3.9.0=37_h47877c9_openblas
  - libnsl=2.0.0=h5eee18b_0
  - libopenblas=0.3.30=pthreads_h94d23a6_2
  - libpng=1.6.50=h421ea60_1
  - libscotch=7.0.4=h2fe6a88_5
  - libsodium=1.0.20=h4ab18f5_0
  - libspral=2025.05.20=hfabd9d1_1
  - libsqlite=3.50.4=h0c1763c_0
  - libstdcxx=15.2.0=h8f9b012_6
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.7.0=he137b08_1
  - libuuid=2.41.2=he9a06e4_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.8=hfdd30dd_0
  - libzlib=1.3.1=hb25bd0a_0
  - lmdb=0.9.31=hd590300_1
  - matplotlib-base=3.10.7=py312he3d6523_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - metis=5.1.0=hd0bcaf9_1007
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py312h06a4308_0
  - mumps-include=5.7.3=h82cca05_10
  - mumps-seq=5.7.3=h27a6a8b_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openjpeg=2.5.3=h55fea9a_1
  - openssl=3.5.4=h26f9b46_0
  - packaging=25.0=py312h06a4308_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.2=pyhc872135_1
  - platformdirs=4.5.0=pyhcf101f3_0
  - pluggy=1.5.0=py312h06a4308_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.1=py312h4c3975b_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.1=py312h06a4308_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pytest=8.4.2=py312h06a4308_0
  - python=3.12.0=hab00c5b_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.12.12=hd8ed1ab_1
  - python_abi=3.12=8_cp312
  - pyzmq=27.1.0=py312hfb55c3c_0
  - qhull=2020.2=h4bd325d_2
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py312h06a4308_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.50.2=hb25bd0a_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - sympy=1.14.0=py312h06a4308_0
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.2=py312h4c3975b_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - unicodedata2=16.0.0=py312h4c3975b_1
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py312h06a4308_0
  - widgetsnbextension=4.0.14=pyhd8ed1ab_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=h387f397_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - absl-py==2.3.1
      - attrs==25.4.0
      - cffi==2.0.0
      - chex==0.1.90
      - clarabel==0.11.1
      - cvxopt==1.3.2
      - cvxpy==1.7.3
      - diffrax==0.7.0
      - dm-haiku==0.0.15
      - dm-tree==0.1.9
      - einshape==1.0
      - equinox==0.12.2
      - immrax==0.2.0
      - immutabledict==4.2.2
      - jax==0.6.2
      - jax-cuda12-pjrt==0.6.2
      - jax-cuda12-plugin==0.6.2
      - jax-verify==1.0
      - jaxlib==0.6.2
      - jaxtyping==0.2.38
      - jinja2==3.1.6
      - jmp==0.0.4
      - joblib==1.5.2
      - lineax==0.0.8
      - linrax==0.1.0
      - markupsafe==3.0.3
      - matplotlib==3.9.4
      - ml-collections==1.1.0
      - ml-dtypes==0.5.3
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.9.1.4
      - nvidia-cuda-cupti-cu12==12.9.79
      - nvidia-cuda-nvcc-cu12==12.9.86
      - nvidia-cuda-nvrtc-cu12==12.9.86
      - nvidia-cuda-runtime-cu12==12.9.79
      - nvidia-cudnn-cu12==9.14.0.64
      - nvidia-cufft-cu12==11.4.1.4
      - nvidia-cusolver-cu12==11.7.5.82
      - nvidia-cusparse-cu12==12.5.10.65
      - nvidia-nccl-cu12==2.28.7
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvshmem-cu12==3.4.5
      - opt-einsum==3.4.0
      - optax==0.2.6
      - optimistix==0.0.11
      - osqp==1.0.5
      - pillow==12.0.0
      - pycddlib==2.1.8.post1
      - pycparser==2.23
      - pypoman==1.1.1
      - pyyaml==6.0.3
      - scipy==1.14.1
      - scs==3.2.9
      - shapely==2.0.7
      - tabulate==0.9.0
      - toolz==1.1.0
      - wadler-lindig==0.1.7
      - wrapt==2.0.0
